In [ ]:
import tensorflow as tf
from tensorflow import keras
from matplotlib import pyplot as plt
import numpy as np

In [ ]:
(X_train,Y_train),(X_test,Y_test)=keras.datasets.cifar10.load_data()

170498071/170498071 ━━━━━━━━━━━━━━━━━━━━ 3674s 22us/step


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
X_train.shape
# (50000, 32, 32, 3)

(50000, 32, 32, 3)

In [ ]:
X_test.shape
# (10000, 32, 32, 3)

(10000, 32, 32, 3)

In [ ]:
Y_train.shape
# (50000, 1)

(50000, 1)

In [ ]:
Y_test.shape
# (10000, 1)

(10000, 1)

In [ ]:
Y_train[:5]
# array([[6],
#        [9],
#        [9],
#        [4],
#        [1]], dtype=uint8)

array([[6],
       [9],
       [9],
       [4],
       [1]], dtype=uint8)

In [ ]:
Y_train = Y_train.reshape(-1,)
Y_train[:5]
# array([6, 9, 9, 4, 1], dtype=uint8)

array([6, 9, 9, 4, 1], dtype=uint8)

In [ ]:
Y_test = Y_test.reshape(-1,)

In [ ]:
Y_test = Y_test.reshape(-1,)

In [ ]:
classes = ["Airplane","Automobile","Bird","Cat","Deer","Dog","Frog","Horse","Ship","Truck"]

In [ ]:
def plot_sample(X,Y,index):
    plt.figure(figsize=(15,2))

In [ ]:
plot_sample(X_train,Y_train,0)

<Figure size 1500x200 with 0 Axes>

In [ ]:
plot_sample(X_train,Y_train,1)

<Figure size 1500x200 with 0 Axes>

In [ ]:
Y_train[:5]
# array([[6],
#        [9],
#        [9],
#        [4],
#        [1]], dtype=uint8)

array([6, 9, 9, 4, 1], dtype=uint8)

In [ ]:
Y_train = Y_train.reshape(-1,)
Y_train[:5]
# array([6, 9, 9, 4, 1], dtype=uint8)

array([6, 9, 9, 4, 1], dtype=uint8)

In [ ]:
Y_test = Y_test.reshape(-1,)


In [ ]:
classes = ["Airplane","Automobile","Bird","Cat","Deer","Dog","Frog","Horse","Ship","Truck"]

In [ ]:
def plot_sample(X,Y,index):
    plt.figure(figsize=(15,2))
    plt.imshow(X[index])
    plt.xlabel(classes[Y[index]])

In [ ]:
X_train_Scaled = X_train/255
X_test_Scaled = X_test/255

In [ ]:
ann = keras.models.Sequential([
    keras.layers.Flatten(input_shape=(32,32,3)),
    keras.layers.Dense(3000,activation='relu'),
    keras.layers.Dense(1000,activation='relu'),
    keras.layers.Dense(10,activation='softmax')
])

ann.compile(
    optimizer='SGD',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

ann.fit(X_train_Scaled,Y_train,epochs=10)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Epoch 1/10
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.3546 - loss: 1.8143
Epoch 2/10
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.4288 - loss: 1.6243
Epoch 3/10
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.4579 - loss: 1.5435
Epoch 4/10
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.4777 - loss: 1.4824
Epoch 5/10
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.4958 - loss: 1.4330
Epoch 6/10
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.5117 - loss: 1.3883
Epoch 7/10
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.5220 - loss: 1.3528
Epoch 8/10
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.5360 - loss: 1.3163
Epoch 9/10
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.5484 - loss: 1.2833
Epoch 10/10
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.5610 - loss: 1.2511


In [ ]:
ann.evaluate(X_test_Scaled,Y_test)
# 313/313 [==============================] - 1s 3ms/step - loss: 1.3347 - accuracy: 0.5...
# [1.3347266912460327, 0.5310000181119812]

313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.4835 - loss: 1.4724


[1.4723960161209106, 0.48350000381469727]

In [ ]:
cnn = keras.models.Sequential([
    keras.layers.Conv2D(filters=32,kernel_size=(3,3),activation='relu',
                         input_shape=(32,32,3)),
    keras.layers.MaxPooling2D(2,2),

    keras.layers.Flatten(),
    keras.layers.Dense(64,activation='relu'),
    keras.layers.Dense(10,activation='softmax')
])

cnn.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

cnn.fit(X_train_Scaled,Y_train,epochs=10)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/10
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - accuracy: 0.4433 - loss: 1.5506
Epoch 2/10
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.5671 - loss: 1.2280
Epoch 3/10
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.6105 - loss: 1.1148
Epoch 4/10
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.6387 - loss: 1.0393
Epoch 5/10
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.6558 - loss: 0.9858
Epoch 6/10
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.6729 - loss: 0.9390
Epoch 7/10
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.6864 - loss: 0.9005
Epoch 8/10
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.6996 - loss: 0.8635
Epoch 9/10
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7117 - loss: 0.8274
Epoch 10/10
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.7229 - loss: 0.7973


In [ ]:
cnn.evaluate(X_test_Scaled,Y_test)
# 313/313 [==============================] - 1s 3ms/step - loss: 1.0488 - accuracy: 0.6470
# [1.0488814296722412, 0.6470000147819519]

313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.6364 - loss: 1.0762


[1.0762100219726562, 0.6363999843597412]

In [ ]:
cnn1 = keras.models.Sequential([
    keras.layers.Conv2D(filters=32,kernel_size=(3,3),activation='relu',input_shape=(32,32,3)),
    keras.layers.MaxPooling2D(2,2),

    keras.layers.Conv2D(filters=64, kernel_size=(3, 3), activation='relu'),
    keras.layers.MaxPooling2D((2, 2)),

    keras.layers.Flatten(),
    keras.layers.Dense(64,activation='relu'),
    keras.layers.Dense(10,activation='softmax')
])

cnn1.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)
cnn1.fit(X_train_Scaled,Y_train,epochs=10)

Epoch 1/10
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - accuracy: 0.4799 - loss: 1.4602
Epoch 2/10
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.6188 - loss: 1.0941
Epoch 3/10
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.6651 - loss: 0.9624
Epoch 4/10
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.6990 - loss: 0.8712
Epoch 5/10
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7212 - loss: 0.8034
Epoch 6/10
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.7397 - loss: 0.7482
Epoch 7/10
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.7578 - loss: 0.6961
Epoch 8/10
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.7739 - loss: 0.6518
Epoch 9/10
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7867 - loss: 0.6070
Epoch 10/10
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.8005 - loss: 0.5683


In [ ]:
y_pred = cnn.predict(X_test)
y_pred[:5]

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step


array([[0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        1.0000000e+00, 0.0000000e+00],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.0000000e+00,
        0.0000000e+00, 2.6975802e-23, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00]], dtype=float32)

In [ ]:
cnn1.evaluate(X_test_Scaled,Y_test)
# 313/313 [==============================] - 1s 3ms/step - loss: 0.9660 - accur...
# [0.9659692645072937, 0.6937999725

313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.6963 - loss: 0.9372


[0.9372022747993469, 0.6963000297546387]

In [ ]:
y_classes = [np.argmax(element) for element in y_pred]
y_classes[:5]
# [0, 8, 0, 8, 3]

[np.int64(3), np.int64(8), np.int64(0), np.int64(0), np.int64(3)]