In [ ]:
import numpy as np
print("numpy loaded succesfully")

numpy loaded succesfully


In [ ]:
np.array(1)
print(type(np.array(1)))#output:<class 'numpy.ndarray'>

<class 'numpy.ndarray'>


In [ ]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr) #output:[1 2 3 4 5]
print(type(arr))#output:<class 'numpy.ndarray'>

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>


In [ ]:
print(len(arr))#output:10

10


In [ ]:
##attribute
print(arr.shape)#output:(10,)

print(arr.ndim)#output:1
print(arr.size)#output:10

(10,)
1
10


In [ ]:
import numpy as np

print(np.arange(0, 10))#start ,stop,step

[0 1 2 3 4 5 6 7 8 9]


In [15]:
np.random.rand(3,4)

array([[0.81386506, 0.00756075, 0.18324763, 0.67517964],
       [0.28906161, 0.7929706 , 0.40516525, 0.71864374],
       [0.50898946, 0.39229129, 0.78003962, 0.27865143]])

In [ ]:
np.random.randint(0,10,10)#start ,stop,step

array([3, 9, 4, 2, 9, 8, 4, 3, 7, 3], dtype=int32)

In [10]:
#zeros
np.zeros((2,4,2),dtype=int)

array([[[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]]])

In [11]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#min,max,argmax,argmin
print(arr)
arr.ravel()
arr.flatten()

min(arr) #py fun
np.min(arr)  #np method max 

#index finding
np.argmax(arr)  #argmin


[ 1  2  3  4  5  6  7  8  9 10]


np.int64(9)

In [18]:
#mean std
print(arr)
arr+arr #3 add

list1=[1,2,3,4,5]
list1+list1 #concat

arr.mean()
arr.std()



[ 1  2  3  4  5  6  7  8  9 10]


np.float64(2.8722813232690143)